name: PersonalLLM
options:
  bundleIdPrefix: com.seanrussell
  deploymentTarget:
    iOS: 18.0

packages:
  PersonalLLMCore:
    path: .

targets:
  PersonalLLM:
    type: application
    platform: iOS
    deploymentTarget: "18.0"
    sources:
      - App/PersonalLLM
    preBuildScripts:
      - name: "Compile and Copy Models"
        script: |
          # Compile CoreML model
          echo "Compiling embeddings model..."
          xcrun coremlcompiler compile "${PROJECT_DIR}/Models/Embeddings/embeddings.mlpackage" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/"

          # Copy LLM model
          echo "Copying Phi-3 model..."
          cp "${PROJECT_DIR}/Models/Phi3Mini/phi3-mini-128k-q4.gguf" "${BUILT_PRODUCTS_DIR}/${PRODUCT_NAME}.app/" || true

          echo "Models compiled and copied to app bundle"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.seanrussell.personalllm
        INFOPLIST_FILE: App/PersonalLLM/Info.plist
        DEVELOPMENT_TEAM: "" # Set your team ID here when needed
        CODE_SIGN_STYLE: Automatic
        TARGETED_DEVICE_FAMILY: "1,2" # iPhone and iPad
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SWIFT_VERSION: "5.9"
        ENABLE_PREVIEWS: YES
    dependencies:
      - package: PersonalLLMCore
        product: PersonalLLMCore
    scheme:
      testTargets:
        - PersonalLLMTests

  PersonalLLMTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - Tests/PersonalLLMCoreTests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: PersonalLLM
      - package: PersonalLLMCore
        product: PersonalLLMCore

schemes:
  PersonalLLM:
    build:
      targets:
        PersonalLLM: all
    run:
      config: Debug
      environmentVariables:
        IDEPreferLogStreaming: "YES"
    test:
      config: Debug
      targets:
        - PersonalLLMTests
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
